#!/usr/bin/env python3
# Copyright (c) 2026 Arm Limited (or its affiliates). All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Compile the Hello-Ethos-U models for one Vela configuration."""

import argparse
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MODEL_DIR = ROOT / "examples" / "Hello-Ethos-U" / "Model"
MODELS = ("hello_world", "tiny_cnn")


def format_bytes(data: bytes, per_line: int = 12) -> str:
    rows = []
    for offset in range(0, len(data), per_line):
        values = "".join(f"0x{value:02x}, " for value in data[offset : offset + per_line])
        rows.append(f"  {values.rstrip()}")
    return "\n".join(rows)


def write_c_array(model: str, data: bytes) -> None:
    output = MODEL_DIR / model / f"{model}_model.c"
    output.write_text(
        "/* Generated by .github/scripts/compile_vela_models.py -- do not edit by hand. */\n"
        "/* SPDX-License-Identifier: Apache-2.0 */\n\n"
        "#include <stdint.h>\n\n"
        f"const uint8_t {model}_int8_vela_tflite[]\n"
        "    __attribute__((aligned(16), section(\"ethos_model\"))) = {\n"
        f"{format_bytes(data)}\n"
        "};\n"
        f"const uint32_t {model}_int8_vela_tflite_len = {len(data)};\n",
        encoding="ascii",
    )


def compile_model(args: argparse.Namespace, model: str) -> None:
    source = MODEL_DIR / model / f"{model}_int8.tflite"
    if not source.is_file():
        raise SystemExit(f"Input model not found: {source}")

    with tempfile.TemporaryDirectory() as temp_dir:
        command = [
            "vela",
            str(source),
            "--accelerator-config",
            args.accelerator_config,
            "--config",
            args.config,
            "--system-config",
            args.system_config,
            "--memory-mode",
            args.memory_mode,
            "--output-dir",
            temp_dir,
        ]
        result = subprocess.run(command, text=True, capture_output=True)
        print(result.stdout, end="")
        if result.returncode:
            print(result.stderr, end="")
            raise SystemExit(f"Vela failed for {source.name}")

        cpu_ops = re.search(r"CPU operators\s*=\s*(\d+)", result.stdout)
        if not cpu_ops or int(cpu_ops.group(1)) != 0:
            raise SystemExit(f"Vela did not fully offload {source.name}")

        compiled = Path(temp_dir) / f"{model}_int8_vela.tflite"
        if not compiled.is_file():
            raise SystemExit(f"Vela output not found: {compiled}")
        data = compiled.read_bytes()
        write_c_array(model, data)
        print(f"Generated {model}_model.c ({len(data)} bytes)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--accelerator-config", required=True)
    parser.add_argument("--config", default="Arm/vela.ini")
    parser.add_argument("--system-config", required=True)
    parser.add_argument("--memory-mode", required=True)
    args = parser.parse_args()

    if shutil.which("vela") is None:
        raise SystemExit("Vela is not installed or is not on PATH")

    for model in MODELS:
        compile_model(args, model)


if __name__ == "__main__":
    main()
