var NAVTREEINDEX0 =
{
"index.html":[],
"index.html":[0],
"index.html#coordinating-the-device-configuration":[0,4],
"index.html#deployment-lifecycle":[0,7],
"index.html#device-packs":[0,1],
"index.html#how-an-ethos-u-inference-runs":[0,3,0],
"index.html#key-terms":[0,2],
"index.html#memory-configuration-terminology":[0,5],
"index.html#related-resources":[0,8],
"index.html#system-configuration-and-memory-modes-at-a-glance":[0,6],
"index.html#system-overview":[0,3],
"index.html#target-audiences":[0,0],
"index.html#target-specific-command-streams":[0,3,1,0],
"index.html#what-is-the-command-stream":[0,3,1],
"pages.html":[],
"rev_hist.html":[1]
};
