var NAVTREEINDEX0 =
{
"index.html":[],
"index.html#add-ml-model-and-configuration-to-version-control":[1,1],
"index.html#add-ml-model-layer":[2,2],
"index.html#add-mlops-information":[2,1],
"index.html#compile-the-ml-model-for-the-device":[3],
"index.html#complete-application-integration":[5],
"index.html#configure-memory-placement-and-the-linker-script":[4],
"index.html#create-the-csolution-project":[2],
"index.html#determine-the-memory-budget":[0,0],
"index.html#driver-build-configuration":[10],
"index.html#driver-weak-hooks":[9],
"index.html#ethos-u-configuration":[7],
"index.html#general-integration-guidance":[1,0],
"index.html#integration-workflow":[1],
"index.html#linker-configuration":[8],
"index.html#starting-point":[0],
"index.html#use-a-project-example-and-add-device":[2,0],
"index.html#validate-and-tune":[6],
"pages.html":[]
};
