var searchData=
[
  ['cache_20attributes_0',['MPU/SAU and cache attributes',['../index.html#mpusau-and-cache-attributes',1,'']]],
  ['characterize_20the_20target_20hardware_20and_20create_20the_20project_1',['Step 1: Characterize the target hardware and create the project',['../index.html#step-1-characterize-the-target-hardware-and-create-the-project',1,'']]],
  ['checklist_2',['Configuration consistency checklist',['../index.html#configuration-consistency-checklist',1,'']]],
  ['cmd_5fstream_5fversion_3',['cmd_stream_version',['../../driver/group__ethosu__driver__structs.html#a27698b004706670a88b442c438991843',1,'ethosu_config']]],
  ['compile_20and_20inspect_20the_20ml_20model_4',['Step 3: Compile and inspect the ML model',['../index.html#step-3-compile-and-inspect-the-ml-model',1,'']]],
  ['compile_20manually_20with_20vela_5',['Compile manually with Vela',['../index.html#compile-manually-with-vela',1,'']]],
  ['compile_20the_20model_20for_20selected_20npu_20and_20vela_20configuration_6',['3. Compile the model for selected NPU and Vela configuration',['../fvp-ethos-setup.html#autotoc_md3-compile-the-model-for-selected-npu-and-vela-configuration',1,'']]],
  ['compile_20with_20an_20mlops_20conversion_20script_7',['Compile with an MLOps conversion script',['../index.html#compile-with-an-mlops-conversion-script',1,'']]],
  ['complete_8',['Troubleshooting an inference that does not complete',['../index.html#troubleshooting-an-inference-that-does-not-complete',1,'']]],
  ['complete_20application_20integration_9',['Complete application integration',['../index.html#complete-application-integration',1,'']]],
  ['config_5fselect_10',['config_select',['../../driver/structethosu__device__user__ops.html#a175b2bedf3384fd298edc407bcdb42ab',1,'ethosu_device_user_ops']]],
  ['configuration_11',['configuration',['../fvp-ethos-setup.html#autotoc_md3-compile-the-model-for-selected-npu-and-vela-configuration',1,'3. Compile the model for selected NPU and Vela configuration'],['../index.html#stage-1-update-the-ethos-u-configuration',1,'Stage 1: Update the Ethos-U configuration'],['../index.html#stage-2-verify-and-update-the-vela-configuration',1,'Stage 2: Verify and update the Vela configuration'],['../index.html#step-2-select-and-verify-the-vela-configuration',1,'Step 2: Select and verify the Vela configuration']]],
  ['configuration_20consistency_20checklist_12',['Configuration consistency checklist',['../index.html#configuration-consistency-checklist',1,'']]],
  ['configuration_20file_20for_20vela_13',['2. Examine configuration file for Vela',['../fvp-ethos-setup.html#autotoc_md2-examine-configuration-file-for-vela',1,'']]],
  ['configuration_20for_20vela_14',['configuration for Vela',['../fvp-ethos-setup.html#examine-memory-mode-configuration-for-vela',1,'Examine memory mode configuration for Vela'],['../fvp-ethos-setup.html#examine-system-configuration-for-vela',1,'Examine system configuration for Vela']]],
  ['configure_20256_20macs_20for_20fvp_20simulation_15',['Configure 256 MACs for FVP simulation',['../index.html#configure-256-macs-for-fvp-simulation',1,'']]],
  ['configure_20ethos_20u_20for_20fvp_20simulation_20models_16',['Configure Ethos-U for FVP Simulation Models',['../fvp-ethos-setup.html',1,'']]],
  ['configure_20memory_20placement_20via_20linker_20script_17',['5. Configure memory placement via linker script',['../fvp-ethos-setup.html#autotoc_md5-configure-memory-placement-via-linker-script',1,'']]],
  ['configure_20memory_20routing_18',['4. Configure memory routing',['../fvp-ethos-setup.html#autotoc_md4-configure-memory-routing',1,'']]],
  ['configure_20the_20platform_20integration_19',['Step 4: Configure the platform integration',['../index.html#step-4-configure-the-platform-integration',1,'']]],
  ['consistency_20checklist_20',['Configuration consistency checklist',['../index.html#configuration-consistency-checklist',1,'']]],
  ['conversion_20script_21',['Compile with an MLOps conversion script',['../index.html#compile-with-an-mlops-conversion-script',1,'']]],
  ['create_20an_20ethos_20u_20application_22',['Tutorial: Create an Ethos-U application',['../index.html#tutorial-create-an-ethos-u-application',1,'']]],
  ['create_20the_20project_23',['Step 1: Characterize the target hardware and create the project',['../index.html#step-1-characterize-the-target-hardware-and-create-the-project',1,'']]],
  ['custom_5fdma_24',['custom_dma',['../../driver/group__ethosu__driver__structs.html#ad1557eaf4f22bc8e02c6d4f189d38965',1,'ethosu_config']]]
];
